/**
 * Resend OTP Controller
 * For TOTP-based login, this endpoint confirms the user should use their authenticator app
 */

const User = require("../../../models/user");

// Lock message
const LOCK_MESSAGE = "Account is locked. Please contact administrator.";

async function resendOTP(req, res, next) {
  try {
    const { userId, email: userEmail } = req.body;

    if (!userId || !userEmail) {
      return res.status(400).json({
        status: false,
        error: "User ID and email are required",
        message: null,
      });
    }

    // Verify user exists
    const user = await User.findById(userId);

    if (!user) {
      return res.status(404).json({
        status: false,
        error: "User not found",
        message: null,
      });
    }

    // Check if account is locked
    if (user.access_control?.is_locked) {
      return res.status(403).json({
        status: false,
        error: "Account is locked",
        message: LOCK_MESSAGE,
        data: {
          isLocked: true,
          reason: user.access_control?.reason
        }
      });
    }

    // Check if account is activated
    if (!user.is_account_activated) {
      return res.status(400).json({
        status: false,
        error: "Account not activated",
        message: "Please use First-Time Login to activate your account.",
      });
    }

    // Check if 2FA is disabled
    if (user.is_2FA_disabled) {
      return res.status(400).json({
        status: false,
        error: "2FA is disabled",
        message: "Two-factor authentication is disabled for this account. You can login directly without TOTP.",
      });
    }

    // For TOTP, we don't resend codes - the user generates them in their authenticator app
    // But we can regenerate the secret if the user lost their device
    // This requires the user to have access to their email for verification
    return res.status(200).json({
      status: true,
      error: null,
      message: "TOTP codes are generated by your authenticator app and change every 30 seconds. If you lost your device, please contact administrator to reset your 2FA.",
      data: {
        userId: user._id,
        email: user.email,
        requiresAction: false
      },
    });

  } catch (error) {
    next(error);
  }
}

module.exports = resendOTP;
