#!/usr/bin/env bash
# The host nginx: one generated file per stack in sites-available (ikaze,
# uat-ikaze), each proxying its public hosts to that stack's container
# addresses, plus the shared port-80 redirect in "default". Sourced by
# update-deploy.sh.

NGINX_DIR="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"
SSL_CERT="/etc/nginx/certs/kigalicity.gov.rw.crt"
SSL_KEY="/etc/nginx/certs/kigalicity.gov.rw.key"
ALL_HOSTS="$PROD_FRONT $UAT_FRONT $UAT_BACKEND_HOST $UAT_EVENTS_HOST $UAT_DCS_HOST $PROD_BACKEND_HOST $PROD_EVENTS_HOST $PROD_DCS_HOST"
INSTALLED_FILES=()

ssl_block() {
  cat <<EOF
    ssl_certificate ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';
    ssl_prefer_server_ciphers on;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
EOF
}

# One public host proxied to one container: WebSocket upgrade for socket.io,
# a long read timeout where data exports and feeds stream.
server_block() {
  local host="$1" service="$2" read_timeout="$3"
  cat <<EOF
# ${LABEL[$service]} of ${STACK} (container ${STACK_PROJECT}/${service}, port ${PORT[$service]})
server {
    listen 443 ssl http2;
    server_name ${host};

$(ssl_block)

    client_max_body_size 100m;

    location / {
        proxy_pass http://${IP[$service]}:${PORT[$service]};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 60s;
        proxy_send_timeout ${read_timeout};
        proxy_read_timeout ${read_timeout};
    }
}

EOF
}

render_stack_nginx() {
  cat <<EOF
# ${STACK} - generated by update-deploy.sh on $(date '+%Y-%m-%d %H:%M:%S'). Do not edit
# by hand: run the script again after the containers restart (their addresses change).

EOF
  server_block "$STACK_FRONT" frontend 600s
  [ -z "$STACK_BACKEND_HOST" ] || server_block "$STACK_BACKEND_HOST" backend 60s
  [ -z "$STACK_EVENTS_HOST" ] || server_block "$STACK_EVENTS_HOST" em-backend 60s
  [ -z "$STACK_DCS_HOST" ] || server_block "$STACK_DCS_HOST" dc-backend 600s
}

render_default_nginx() {
  cat <<EOF
# Generated by update-deploy.sh on $(date '+%Y-%m-%d %H:%M:%S'): every public host is
# sent to HTTPS. The HTTPS servers live in the per-stack files (ikaze, uat-ikaze).
server {
    listen 80;
    server_name $(printf '%s\n' $ALL_HOSTS | sort -u | tr '\n' ' ' | sed -E 's/ $//');

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}
EOF
}

# Writes a file into sites-available (backup kept) and enables it.
install_nginx_file() {
  local name="$1"
  local content="$2"
  local target="$NGINX_DIR/$name"
  local backup
  if [ "$DRY_RUN" = 1 ]; then
    printf '\n----- %s -----\n%s\n' "$target" "$content"
    return 0
  fi
  if [ -f "$target" ] && [ "$(cat "$target")" = "$content" ]; then
    ok "$target unchanged"
  else
    backup="$target.bak.$STAMP"
    [ -f "$target" ] && cp "$target" "$backup" && ok "previous $name kept at $backup"
    printf '%s\n' "$content" > "$target"
    ok "$target written"
  fi
  [ -e "$NGINX_ENABLED/$name" ] || ln -s "$target" "$NGINX_ENABLED/$name"
  INSTALLED_FILES+=("$name")
}

write_stack_nginx() {
  log "nginx file for $STACK"
  install_nginx_file "$STACK" "$(render_stack_nginx)"
}

# Tests and restarts nginx once every processed stack has its file. On a
# failed test every file written in this run is put back from its backup.
apply_nginx() {
  log "Applying nginx"
  install_nginx_file default "$(render_default_nginx)"
  [ "$DRY_RUN" = 1 ] && return 0
  if nginx -t; then
    if systemctl restart nginx 2>/dev/null || nginx -s reload; then ok "nginx restarted"; else die "nginx could not be restarted"; fi
  else
    local name
    for name in "${INSTALLED_FILES[@]}"; do
      [ -f "$NGINX_DIR/$name.bak.$STAMP" ] && cp "$NGINX_DIR/$name.bak.$STAMP" "$NGINX_DIR/$name"
    done
    die "the generated nginx files failed 'nginx -t' - the previous files were restored"
  fi
}

# Every public host of the stack against its container.
verify_stack() {
  log "Public addresses of $STACK"
  local service host direct public result
  printf '   %-14s %-22s %-8s %-8s %s\n' "SERVICE" "CONTAINER" "DIRECT" "URL" "RESULT"
  for service in "${SERVICES[@]}"; do
    case "$service" in
      frontend) host="$STACK_FRONT" ;;
      backend) host="$STACK_BACKEND_HOST" ;;
      em-backend) host="$STACK_EVENTS_HOST" ;;
      dc-backend) host="$STACK_DCS_HOST" ;;
    esac
    direct="$(http_status "http://${IP[$service]}:${PORT[$service]}${PROBE[$service]}")"
    if [ -z "$host" ]; then
      if [ "$direct" != "000" ]; then result="reached through https://${STACK_FRONT} (no host of its own)"; else result="container not answering - docker compose -p ${STACK_PROJECT} logs -f ${service}"; fi
      printf '   %-14s %-22s %-8s %-8s %s\n' "$service" "${IP[$service]}:${PORT[$service]}" "$direct" "-" "$result"
      continue
    fi
    public="$(public_status "https://${host}${PROBE[$service]}")"
    case "$public" in
      000) result="URL not reachable at all (DNS record or certificate for ${host}) - use http://${IP[$service]}:${PORT[$service]} meanwhile" ;;
      502|503|504) if [ "$direct" != "000" ]; then result="nginx cannot reach the container although it answers directly - run this script again"; else result="container not answering - docker compose -p ${STACK_PROJECT} logs -f ${service}"; fi ;;
      *) result="OK - https://${host}" ;;
    esac
    printf '   %-14s %-22s %-8s %-8s %s\n' "$service" "${IP[$service]}:${PORT[$service]}" "$direct" "$public" "$result"
  done
}
